name: Run Python Script for Air Pollution Data

on:
  schedule:
    # Runs daily at 11:00 PM IST (17:30 PM UTC)
    - cron: '30 17 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you're using locally

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # or install pymongo directly

    - name: Run Python script
      run: |
        python app.py  # Run your script
