name: Daily Air Pollution Data Collection

on:
  schedule:
    - cron: '40 23 * * *'  # This runs the script every day at 11:40 PM UTC
  workflow_dispatch:

jobs:
  collect_data:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies from the requirements.txt

    # Run the Python script
    - name: Run the data collection script
      run: |
        python app.py  # Run the app.py script to collect the data